// GENERATED FROM THE REDROB DESIGN SYSTEM -- DO NOT EDIT.
// source: third_party/redrob-ui/tokens.json  sha256 12ff082d7319df33…
//
// Regenerate with: python3 tools/generate_design_tokens.py
// Verify with:     python3 tools/generate_design_tokens.py --check
//
// A value changed here is a value that disagrees with every other Redrob product. The numbers
// are the delivery's own, resolved per theme by its generator, not re-derived here.

import QtQuick

QtObject {
    // Which ground the window is on. Canvas paints dark, and every binding below follows this
    // rather than a build flag: the app can be dark while the desktop is light.
    property bool dark: true

    readonly property color accentGreen1: "#d6ffe1"
    readonly property color accentGreen2: "#a6ffbf"
    readonly property color accentGreen3: "#29e474"
    readonly property color accentGreen4: "#00864a"
    readonly property color accentGreen5: "#004829"
    readonly property color accentLime1: "#f2ffc3"
    readonly property color accentLime2: "#e5ff81"
    readonly property color accentLime3: "#cffd21"
    readonly property color accentLime4: "#89ad00"
    readonly property color accentLime5: "#2f5f00"
    readonly property color accentOrange1: "#ffedda"
    readonly property color accentOrange2: "#ffd5ab"
    readonly property color accentOrange3: "#ff9c1b"
    readonly property color accentOrange4: "#ae5100"
    readonly property color accentOrange5: "#5c2d00"
    readonly property color accentPink1: "#ffe3fc"
    readonly property color accentPink2: "#ffb2f6"
    readonly property color accentPink3: "#ff39ba"
    readonly property color accentPink4: "#8a0061"
    readonly property color accentPink5: "#380037"
    readonly property color accentRed1: "#ffe1e1"
    readonly property color accentRed2: "#ffabab"
    readonly property color accentRed3: "#ff4b4b"
    readonly property color accentRed4: "#a31310"
    readonly property color accentRed5: "#560100"
    readonly property color accentSky1: "#e4f0ff"
    readonly property color accentSky2: "#bad9ff"
    readonly property color accentSky3: "#2f8dff"
    readonly property color accentSky4: "#0e51b6"
    readonly property color accentSky5: "#002a68"
    readonly property color accentTeal1: "#dcfffe"
    readonly property color accentTeal2: "#b9fffd"
    readonly property color accentTeal3: "#6ff4f0"
    readonly property color accentTeal4: "#00b5c2"
    readonly property color accentTeal5: "#006a7a"
    readonly property color accentViolet1: "#f2e9ff"
    readonly property color accentViolet2: "#d4b3ff"
    readonly property color accentViolet3: "#8944ff"
    readonly property color accentViolet4: "#4500ac"
    readonly property color accentViolet5: "#140042"
    readonly property color accentYellow1: "#fff7cc"
    readonly property color accentYellow2: "#ffed94"
    readonly property color accentYellow3: "#ffda1e"
    readonly property color accentYellow4: "#d2a100"
    readonly property color accentYellow5: "#734f00"
    readonly property color actionPrimary: "#2b52ff"
    readonly property color actionPrimaryHover: dark ? "#507fff" : "#1733d5"
    readonly property color blue1: "#eef4ff"
    readonly property color blue10: "#030c34"
    readonly property color blue2: "#d9e6ff"
    readonly property color blue3: "#bad2ff"
    readonly property color blue4: "#8aafff"
    readonly property color blue5: "#507fff"
    readonly property color blue6: "#2b52ff"
    readonly property color blue7: "#1733d5"
    readonly property color blue8: "#09209c"
    readonly property color blue9: "#061460"
    readonly property color borderAi: dark ? "#09209c" : "#bad2ff"
    readonly property color borderStrong: "#7c8390"
    readonly property color borderSubtle: dark ? "#292e37" : "#dfe2e8"
    readonly property color focusRing: dark ? "#8aafff" : "#2b52ff"
    readonly property color gray1: "#f8f9fb"
    readonly property color gray2: "#eff1f4"
    readonly property color gray3: "#dfe2e8"
    readonly property color gray4: "#cbcfd7"
    readonly property color gray5: "#aab0bb"
    readonly property color gray6: "#7c8390"
    readonly property color gray7: "#576071"
    readonly property color gray8: "#292e37"
    readonly property color gray9: "#141719"
    readonly property color inkBrand: dark ? "#8aafff" : "#1733d5"
    readonly property color inkMuted: dark ? "#838a97" : "#686e78"
    readonly property color inkOnBrand: "#ffffff"
    readonly property color inkPrimary: dark ? "#f8f9fb" : "#0a0b0c"
    readonly property color inkSecondary: dark ? "#aab0bb" : "#576071"
    readonly property color overlayScrim: dark ? "rgba(0, 0, 0, 0.66)" : "rgba(10, 11, 12, 0.55)"
    readonly property color productBrowser: "#f14aa8"
    readonly property color productChat: "#149ca0"
    readonly property color productCode: "#02a252"
    readonly property color productDesign: "#c162f4"
    readonly property color productDesk: "#d87101"
    readonly property color productOffice: "#fe4d3e"
    readonly property color productRouter: "#1194dd"
    readonly property color redrobBlack: "#0a0b0c"
    readonly property color redrobWhite: "#ffffff"
    readonly property color statusDanger: dark ? "#ff4b4b" : "#a31310"
    readonly property color statusInfo: dark ? "#2f8dff" : "#0e51b6"
    readonly property color statusSuccess: dark ? "#29e474" : "#00864a"
    readonly property color statusWarning: dark ? "#ff9c1b" : "#ae5100"
    readonly property color surfaceAi: dark ? "#030c34" : "#eef4ff"
    readonly property color surfaceBase: dark ? "#0a0b0c" : "#ffffff"
    readonly property color surfaceBrand: "#2b52ff"
    readonly property color surfaceBrandSubtle: dark ? "#030c34" : "#eef4ff"
    readonly property color surfaceMaterial: dark ? "rgba(20, 23, 25, 0.86)" : "rgba(255, 255, 255, 0.82)"
    readonly property color surfaceRaised: dark ? "#141719" : "#f8f9fb"
    readonly property color surfaceSunken: dark ? "#1c1f26" : "#eff1f4"
}
