#!/usr/bin/env python3
"""Build the Redrob Canvas product icon from the design system's own tile geometry.

What was here before was a hand-drawn letter R in an invented blue-violet gradient with a teal dot.
10-logo.md: the artwork is "Never redrawn, restretched, recolored or otherwise modified" -- and a typed
R is not a modification of the mark, it is a different mark.

Geometry and rules are assets/Products/README.md:

  Tile        square top-left corner, 22% radius on the other three from 48px up; 19% at 32px.
  Symbol      the shipped file, Solid White, on every tile. LIFTED as a path from a shipped product
              icon rather than retyped, so it cannot drift.
  Doorway     "Redrob's doorway is empty. Something in the doorway means a product." Canvas's is a nib.
              Every shipped glyph is FILLED white with no stroke, and Desk's folder measures
              x 212..300, y 207..314, which is the room a glyph has.
  Tile colour Design's band. 20-color.md closes the spectrum at seven and states there is no eighth
              product colour; 10-logo.md's way out is that a new product ships as a feature of the band
              it fits, and Canvas makes things. Pinned in DESIGN_SYSTEM_PIN.json.

Two files are written, because at 32px and below "the doorway is two or three pixels wide" and the
README asks for tile and symbol only there.

--check verifies the committed SVGs are what this script produces, which is what CI can run without the
delivery present.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
DELIVERY = pathlib.Path.home() / "workplace/redrob-design-system/assets/Products"
ICONS = ROOT / "resources/icons"
MASTER = ICONS / "redrob-canvas.svg"
SMALL = ICONS / "redrob-canvas-small.svg"
# macOS draws every app icon on Apple's grid: the tile is 824 of a 1024 canvas, centred, and the rest
# is transparent. The browser's icon is compiled from an Icon Composer file, so macOS places it on
# that grid itself; a Qt window icon is drawn as given, so the full-bleed master stood about a fifth
# larger than every other Dock icon. This variant carries the same tile on the grid.
MACOS = ICONS / "redrob-canvas-macos.svg"
MACOS_TILE = 824 / 1024
MACOS_OFFSET = 512 * (1 - MACOS_TILE) / 2
PIN = ROOT / "DESIGN_SYSTEM_PIN.json"

TILE = ("M0 0H399.36A112.64 112.64 0 0 1 512 112.64V399.36A112.64 112.64 0 0 1 399.36 512"
        "H112.64A112.64 112.64 0 0 1 0 399.36Z")
TILE_32 = ("M0 0H414.72A97.28 97.28 0 0 1 512 97.28V414.72A97.28 97.28 0 0 1 414.72 512"
           "H97.28A97.28 97.28 0 0 1 0 414.72Z")

# A nib: a tapered blade with its slit and vent, on the gate's waist, inside x 212..300, y 207..314.
NIB = (
    '<path d="M256 210L294 268L256 312L218 268Z" fill="#FFFFFF" fill-rule="evenodd"/>'
    '<path d="M249 252H263V300L256 310L249 300Z" fill="#C162F4"/>'
    '<circle cx="256" cy="246" r="9" fill="#C162F4"/>'
)


def symbol_path() -> str:
    source = DELIVERY / "redrob-design-icon.svg"
    if not source.exists():
        sys.exit(f"design system delivery not found: {source}\n"
                 "This script regenerates the icon and needs the delivery. Use --check to verify the"
                 " committed files without it.")
    found = re.search(r'(<path d="M54\.4[^/]*?/>)', source.read_text(encoding="utf-8"))
    if not found:
        sys.exit(f"could not lift the symbol path out of {source.name}")
    return found.group(1)


def render(tile_colour: str) -> tuple[str, str, str]:
    symbol = symbol_path()
    nib = NIB.replace("#C162F4", tile_colour)
    head = ("<!-- SPDX-License-Identifier: GPL-3.0-or-later -->\n"
            "<!-- GENERATED by tools/build_app_icon.py from the Redrob design system. DO NOT EDIT. -->\n")
    master = (
        f'{head}<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"'
        ' viewBox="0 0 512 512" role="img" aria-label="Redrob Canvas">'
        f'<title>Redrob Canvas</title><path d="{TILE}" fill="{tile_colour}"/>{symbol}{nib}</svg>\n'
    )
    small = (
        f'{head}<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"'
        ' viewBox="0 0 512 512" role="img" aria-label="Redrob Canvas">'
        f'<title>Redrob Canvas</title><path d="{TILE_32}" fill="{tile_colour}"/>{symbol}</svg>\n'
    )
    macos = (
        f'{head}<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"'
        ' viewBox="0 0 512 512" role="img" aria-label="Redrob Canvas">'
        f'<title>Redrob Canvas</title>'
        f'<g transform="translate({MACOS_OFFSET:g} {MACOS_OFFSET:g}) scale({MACOS_TILE!r})">'
        f'<path d="{TILE}" fill="{tile_colour}"/>{symbol}{nib}</g></svg>\n'
    )
    return master, small, macos


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="verify the committed icons against their pinned hashes, offline")
    args = parser.parse_args()

    pin_text = PIN.read_text(encoding="utf-8")
    pin = json.loads(pin_text)
    tile_colour = pin["product_band"]["tile"]
    pinned = {entry["file"]: entry for entry in pin["generated"]
              if entry["file"].startswith("resources/icons/")}

    if args.check:
        # Verification must NOT need the design system delivery. CI has the repository and nothing
        # else, so checking by REGENERATING would fail there for want of a file that is not ours to
        # ship -- which is exactly how this first broke. The committed bytes are pinned instead, so a
        # hand edit fails here while regeneration stays the only path that needs the delivery.
        failures = []
        for relative, entry in sorted(pinned.items()):
            path = ROOT / relative
            if not path.exists():
                failures.append(f"{relative} is missing but is pinned in DESIGN_SYSTEM_PIN.json")
                continue
            actual = hashlib.sha256(path.read_bytes()).hexdigest()
            if actual != entry.get("sha256"):
                failures.append(
                    f"{relative} does not match its pin.\n"
                    f"      expected {entry.get('sha256')}\n      actual   {actual}\n"
                    f"      Regenerate it with tools/build_app_icon.py (needs the design system"
                    f" delivery), rather than editing it."
                )
            elif tile_colour not in path.read_text(encoding="utf-8"):
                failures.append(f"{relative} does not carry the pinned tile colour {tile_colour}")
        if failures:
            for failure in failures:
                print(failure, file=sys.stderr)
            return 1
        print(f"{len(pinned)} icons match their pins, tile {tile_colour}")
        return 0

    master, small, macos = render(tile_colour)
    MASTER.write_text(master, encoding="utf-8", newline="\n")
    SMALL.write_text(small, encoding="utf-8", newline="\n")
    MACOS.write_text(macos, encoding="utf-8", newline="\n")
    # Regeneration owns the pin: writing the file and recording its hash in one step is what keeps the
    # two from disagreeing. Only each entry's sha256 value is replaced in the text; dumping the parsed
    # JSON back would reflow the hand-laid one-line entries of every other pin.
    for path in (MASTER, SMALL, MACOS):
        relative = str(path.relative_to(ROOT))
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        pattern = re.compile(r'("file": "' + re.escape(relative) + r'",(?:[^{}]*?)"sha256": ")[0-9a-f]*(")')
        pin_text, count = pattern.subn(lambda m: m.group(1) + digest + m.group(2), pin_text)
        if count != 1:
            sys.exit(f"{relative} has no single sha256 entry in {PIN.name}; add one, then rerun")
    PIN.write_text(pin_text, encoding="utf-8", newline="\n")
    print(f"wrote {MASTER.relative_to(ROOT)}, {SMALL.relative_to(ROOT)} and {MACOS.relative_to(ROOT)},"
          f" tile {tile_colour},"
          f" and recorded their hashes in {PIN.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
